### ISSUE TITLE
404's on github readme

### ISSUE THREAD

**Issue by clintonhalpin** [mariuszostrowski/subway#1]
Can't see the icons :(

![screen shot 2015-02-11 at 1 38 45 pm](https://cloud.githubusercontent.com/assets/523933/6153549/57748884-b1f3-11e4-819d-cbb9fffc4914.png)

**Comment by pixle** [comment]
Strange, for me everything is ok :)
![2015-02-11 07 41 19 pm](https://cloud.githubusercontent.com/assets/3432291/6153614/226cdf50-b226-11e4-9800-380dc88436f1.png)

**Comment by clintonhalpin** [comment]
@pixle Is this a link to a private repo? https://github.com/pixle/subwayimages/ Looks like thats where the images are pointing to.

**Comment by pixle** [comment]
Preview images now are on GitHub, should be ok. Thx!

**Comment by clintonhalpin** [comment]
Looks great!
