### ISSUE TITLE
Usage License question

### ISSUE THREAD

**Issue by ScarletSkyFury** [mariuszostrowski/subway#4]
Hello,

I am a mobile app developer and I recently came across this website and instantly became interested in the Subway Icon Set.

On "http://www.pixle.pl/" where i initially saw it, it said that the Icon Set is available to purchase, but when i entered the link "https://github.com/mariuszostrowski/subway" I did not see any option to purchase the set, but instead found a button to download the zipped file containing the set within.
Inside the zipped file i found a document called "License" linking me to this page (http://creativecommons.org/licenses/by/4.0/)

So my question is, as a developer, am I free to use this set in my apps(giving credit to the original owner of course)? Or must I pay some kind of license?

Thanks in advance
Any clarification on this would be great,

Paul

**Comment by mariuszostrowski** [comment]
It's free :)
